name: Build Windows 2025 Docker Image

on:
  push:
    branches: [ "prepare-windows-2025-image" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build windows.ltsc2025 --file windows.ltsc2025/Dockerfile --tag worker-tools-windows-ltsc2025:$(date +%s)
